config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants do
    resources :reviews, only: %i[new create destroy] # Destroy va fuera pero no termino de entender why, para optimizar
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
# This is the base of our app
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :category, :address, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :grab_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show; end

  def create
    @restaurant = Restaurant.new(review_restaurant)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit; end

  def update
    @restaurant.update(review_restaurant)
    redirect_to restaurant_path, status: :see_other
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurant_path, status: :see_other
  end

  private

  def grab_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def review_restaurant
    params.require(:restaurant).permit(:name, :phone_number, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :grab_restaurant, only: %i[new create destroy]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_review)
    @review.restaurant = @restaurant # Importanteeeee para linkearlo
    @review.save
    redirect_to restaurant_path(grab_restaurant), status: :see_other
  end

  def destroy
    @review.destroy
    redirect_to restaurant_path, status: :see_other
  end

  private

  def grab_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_review
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :phone_number %>
<%= f.input :category %>
<%= f.submit "Submit", class: "btn btn-success" %>
<% end %>

app/views/restaurants/_list.html.erb
<div class="container row">
  <% restaurants.each do |restaurant| %>
    <div class="container col-3 mt-2">
      <div class="card card-bg-color" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= restaurant.name.capitalize %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= restaurant.category.capitalize %></h6>
          <p class="card-text"><%= restaurant.address %></p>
          <p class="card-text"><%= restaurant.phone_number %></p>
          <p><%= link_to "Details", restaurant, {:class => "card-link"} %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
<%= render "restaurants/form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Welcome to our Restaurant display!</h1>
  <%= render "restaurants/list", restaurants: @restaurants %>
</div>

app/views/restaurants/new.html.erb
<%= render "restaurants/form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<p><%= link_to "Go back", restaurants_path, {:class => "card-link"} %></p>

<div class="container row">
  <div class="container col-3 mt-2">
    <div class="card card-bg-color" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= @restaurant.name.capitalize %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= @restaurant.category.capitalize %></h6>
        <p class="card-text"><%= @restaurant.address %></p>
        <p class="card-text"><%= @restaurant.phone_number %></p>
        <div class="d-flex justify-content-around">
        <p><%= link_to "Edit info", edit_restaurant_path(@restaurant), {:class => "card-link"} %></p>
        <p><%= link_to "Leave a Review!", new_restaurant_review_path(@restaurant), {:class => "card-link"} %></p>
        </div>

      </div>
    </div>
  </div>
</div>
<h3>Reviews</h3>

<% @restaurant.reviews.each do |review| %>
<div class="container row">
    <div class="card border-light mb-3 col-6" style="max-width: 18rem;">
      <div class="card-header">On <%= review.created_at.strftime("Rated on %m/%d/%Y") %></div>
      <div class="card-body">
        <h5 class="card-title"><%= review.rating %> ⭐</h5>
        <p class="card-text"><%= review.content %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>
<%= simple_form_for([@restaurant, @review]) do |f| %>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.submit "Submit review!", class: "btn btn-success" %>
<% end %>